FROM nginx:alpine

WORKDIR /app

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY fakestoreapi.crt /etc/nginx/fakestoreapi.ru/fakestoreapi.crt
COPY fakestoreapi.key /etc/nginx/fakestoreapi.ru/fakestoreapi.key

RUN nginx -T

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]